DepositBanking/Volo.Luiza_Kishoyan.DepositBanking/Areas/Admin/Controllers/BanksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DepositBanking.Repository.DepositBankingEntityModels;
using System.IO;
using AutoMapper;
using Volo.Luiza_Kishoyan.DepositBanking.Areas.Admin.ViewModels.BankViewModels;

namespace Volo.Luiza_Kishoyan.DepositBanking.Areas.Admin.Controllers
{
    public class BanksController : BaseController
    {
        public ActionResult Index()
        {
            Mapper.Initialize(b => b.CreateMap<Bank, BankIndexViewModel>());
            var banks = Mapper.Map<IEnumerable<Bank>, IEnumerable<BankIndexViewModel>>(depositBankingRepository.GetAll<Bank>());

            return View(banks);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mapper.Initialize(b => b.CreateMap<Bank, BankDetailsViewModel>()
                .ForMember("State", opt => opt.MapFrom(n => n.DestroyDate == null ? "Active" : "Not Active")));
            BankDetailsViewModel bank = Mapper.Map<Bank, BankDetailsViewModel>(depositBankingRepository.GetById<Bank>(id.Value));

            if (bank == null)
            {
                return HttpNotFound();
            }
            return View(bank);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,OrganizationHead,Address,Branch,Phone,Fax,Email,SWIFT,TPIN")] BankCreateViewModel bank, HttpPostedFileBase Logo)
        {
            if (ModelState.IsValid)
            {
                string fileName = "";
                if (Logo != null)
                {
                    var path = Path.Combine(Server.MapPath("~/Content/BankLogos"), Logo.FileName);
                    fileName = Path.GetFileNameWithoutExtension(Logo.FileName);
                    Logo.SaveAs(path);
                }
                else
                {
                    fileName = null;
                }
                Mapper.Initialize(b => b.CreateMap<BankCreateViewModel, Bank>()
                    .ForMember("Logo", opt => opt.MapFrom(n => fileName))
                    .ForMember("CreationDate", opt => opt.MapFrom(d => DateTime.Now)));

                Bank newbank = Mapper.Map<BankCreateViewModel, Bank>(bank);

                depositBankingRepository.Create<Bank>(newbank);
                return RedirectToAction("Index");
            }
            return View(bank);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mapper.Initialize(b => b.CreateMap<Bank, BankEditViewModel>());
            BankEditViewModel bank = Mapper.Map<Bank, BankEditViewModel>(depositBankingRepository.GetById<Bank>(id.Value));

            if (bank == null)
            {
                return HttpNotFound();
            }
            return View(bank);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BankEditViewModel bank, HttpPostedFileBase Logo)
        {
            if (ModelState.IsValid)
            {
                string fileName = "";
                if (Logo != null)
                {
                    var path = Path.Combine(Server.MapPath("~/Content/BankLogos"), Logo.FileName);
                    fileName = Path.GetFileNameWithoutExtension(Logo.FileName);
                    Logo.SaveAs(path);
                }
                else
                {
                    fileName = null;
                }
                Mapper.Initialize(b => b.CreateMap<BankEditViewModel, Bank>()
                    .ForMember("Logo", opt => opt.MapFrom(n => fileName)));
                Bank newbank = Mapper.Map<BankEditViewModel, Bank>(bank);

                depositBankingRepository.Update<Bank>(newbank);
                return RedirectToAction("Index");
            }
            return View(bank);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mapper.Initialize(b => b.CreateMap<Bank, BankDetailsViewModel>()
                .ForMember("State", opt => opt.MapFrom(n => n.DestroyDate == null ? "Active" : "Not Active")));
            BankDetailsViewModel bank = Mapper.Map<Bank, BankDetailsViewModel>(depositBankingRepository.GetById<Bank>(id.Value));

            if (bank == null)
            {
                return HttpNotFound();
            }

            return View(bank);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bank bank = depositBankingRepository.GetById<Bank>(id);

            if (bank == null)
            {
                return HttpNotFound();
            }
            else
            {
                bank.DestroyDate = DateTime.Now;
            }

            depositBankingRepository.Update<Bank>(bank);

            var investments = depositBankingRepository.GetAll<Investment>().Where(b => b.BankId == id).ToList();
            if (investments == null)
            {
                return HttpNotFound();
            }
            else
            {
                foreach (var item in investments)
                {
                    item.BankState = "Not Active";
                    depositBankingRepository.Update<Investment>(item);
                }
            }
            return RedirectToAction("Index");
        }
    }
}

DepositBanking/Volo.Luiza_Kishoyan.DepositBanking/Controllers/BanksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using DepositBanking.Repository.DepositBankingEntityModels;
using AutoMapper;
using Volo.Luiza_Kishoyan.DepositBanking.ViewModels.BankViewModels;

namespace Volo.Luiza_Kishoyan.DepositBanking.Controllers
{
    public class BanksController : Areas.Admin.Controllers.BaseController
    {
        public ActionResult Index()
        {
            Mapper.Initialize(b => b.CreateMap<Bank, BankIndexViewModel>());
            var banks = Mapper.Map<IEnumerable<Bank>, IEnumerable<BankIndexViewModel>>(depositBankingRepository.GetAllActiveBanks());
          
            return View(banks);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mapper.Initialize(b => b.CreateMap<Bank, BankDetailsViewModel>()
                .ForMember("State", opt => opt.MapFrom(n => n.DestroyDate==null ? "Active" : "Not Active")));
            BankDetailsViewModel bank = Mapper.Map<Bank, BankDetailsViewModel>(depositBankingRepository.GetById<Bank>(id.Value));
            
            if (bank == null)
            {
                return HttpNotFound();
            }

            return View(bank);
        }
      
    }
}

DepositBanking/Volo.Luiza_Kishoyan.DepositBanking/Areas/Admin/Views/Banks/Create.cshtml
@model Volo.Luiza_Kishoyan.DepositBanking.Areas.Admin.ViewModels.BankViewModels.BankCreateViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Banks", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bank</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrganizationHead, "Organization Head", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrganizationHead, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrganizationHead, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Branch, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Branch, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Branch, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SWIFT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SWIFT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SWIFT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TPIN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TPIN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TPIN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <Input type="file" id="Logo" name="Logo" accept=".jpg" />
                @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DepositBanking/Volo.Luiza_Kishoyan.DepositBanking/Areas/Admin/Views/Banks/Delete.cshtml
@model Volo.Luiza_Kishoyan.DepositBanking.Areas.Admin.ViewModels.BankViewModels.BankDetailsViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bank</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizationHead)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizationHead)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Branch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Branch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SWIFT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SWIFT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TPIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TPIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-success" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DepositBanking/Volo.Luiza_Kishoyan.DepositBanking/Areas/Admin/Views/Banks/Details.cshtml
@model Volo.Luiza_Kishoyan.DepositBanking.Areas.Admin.ViewModels.BankViewModels.BankDetailsViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Bank</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizationHead)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizationHead)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Branch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Branch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SWIFT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SWIFT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TPIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TPIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<hr />
<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#Investments">Investments</a></li>
</ul>

<div class="tab-content">
    <div id="Investments" class="tab-pane fade in active"> 
        <table class="table">
            <tr>
                <th>
                    Depositor
                </th>
                <th>
                    Deposit
                </th>
                <th>
                    Rate
                </th>
                <th>
                    Amount
                </th>
                <th>
                    StartDate
                </th>
                <th>
                    EndDate
                </th>
                <th>
                    Currency
                </th>
                <th>
                    Duration
                </th>
                <th>
                    FinalAmount
                </th>
                <th>
                    DepositorState
                </th>
                <th>
                    CreationDate
                </th>
                <th>
                    DestroyDate
                </th>
               
            </tr>

            @foreach (var item in Model.Investments)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Depositor.Name) @Html.DisplayFor(modelItem => item.Depositor.Surname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Rate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Currency)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Duration)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FinalAmount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DepositorState)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreationDate)
                    </td>
                    <td>
                        @if (item.DestroyDate == null) { <p> Active</p> } 
                        @Html.DisplayFor(modelItem => item.DestroyDate)
                    </td>
                </tr>
            }

        </table>

    </div>

</div>

DepositBanking/Volo.Luiza_Kishoyan.DepositBanking/Areas/Admin/Views/Banks/Edit.cshtml
@model Volo.Luiza_Kishoyan.DepositBanking.Areas.Admin.ViewModels.BankViewModels.BankEditViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Banks", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bank</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CreationDate)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrganizationHead, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrganizationHead, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrganizationHead, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Branch, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Branch, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Branch, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SWIFT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SWIFT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SWIFT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TPIN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TPIN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TPIN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <Input type="file" id="" name="Logo" value="~/Content/BankLogos/@(Model.Logo + ".jpg")" accept=".jpg" />
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

DepositBanking/Volo.Luiza_Kishoyan.DepositBanking/Areas/Admin/Views/Banks/Index.cshtml
@model IEnumerable<Volo.Luiza_Kishoyan.DepositBanking.Areas.Admin.ViewModels.BankViewModels.BankIndexViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Banks</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p><div class="container-fluid">
    <div class="row">

        @foreach (var item in Model)
        {
            <div class="col-xs-12 col-md-4 col-lg-2">
               <img src="~/Content/BankLogos/@(item.Logo + ".jpg")" /> <br>
                @Html.DisplayFor(Modelitem => item.Name) <br>

                @Html.ActionLink("Edit", "Edit", new { area = "Admin", controller = "Banks", Id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { area = "Admin", controller = "Banks", id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { area = "Admin", controller = "Banks", id = item.Id }) 

            </div>
        }
    </div>
</div>